### ISSUE TITLE
Boucle infinie lors de la reception d'un signal (SIGTERM)

### ISSUE THREAD

**Issue by Ousret** [DanAurea/Tactics-Arena#1]
Envoyer le signal SIGTERM avec CTRL+C lancera une boucle infinie.
Ce code doit mettre fin au programme, ce n'est pas le cas ici.

``` c
void interrupt(int signal){
    freeAll();
        //...
    raise(SIGINT); // Envoie un signal d'interruption
}
```

Vous recevez déjà un signal d'interruption, raise(SIGINT) ne terminera pas votre application, exit(int code) le fera.

Bon travail sinon!

**Comment by DanAurea** [comment]
C'est bien ce que j'avais compris en regardant la doc alors mais je ne comprenais pas pourquoi raise interrompt tout de même l'exécution du programme. Ca sera fix très rapidement là priorité au rapport.
